# Generated by Django 5.1 on 2024-08-12 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcalim', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoria',
            table='categoria',
        ),
    ]
