# Generated by Django 5.1 on 2024-08-13 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcalim', '0003_subcategoria'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoria',
            table='Categoria',
        ),
    ]
