# Generated by Django 5.1 on 2024-08-13 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcalim', '0004_alter_categoria_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoria',
            table='categoria',
        ),
        migrations.AlterModelTable(
            name='subcategoria',
            table='subcategoria',
        ),
    ]
