# Generated by Django 5.1 on 2024-08-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcalim', '0006_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='categoria_icon',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
