# Generated by Django 5.1 on 2024-08-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcalim', '0007_categoria_categoria_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='subcategoria_imagen',
            field=models.ImageField(default='imagenes/subcategoria/default.png', upload_to='imagenes/subcategoria/'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='categoria_icon',
            field=models.CharField(default='imagenes/subcategoria/default.jpg', max_length=50),
            preserve_default=False,
        ),
    ]
