# Generated by Django 5.1 on 2024-08-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcalim', '0008_subcategoria_subcategoria_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categoria_icon',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
