# Generated by Django 5.1 on 2024-08-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcalim', '0009_alter_categoria_categoria_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoria',
            name='subcategoria_imagen',
            field=models.ImageField(upload_to='imagenes/subcategoria/'),
        ),
    ]
