# Generated by Django 5.1 on 2024-08-16 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcalim', '0011_higiene'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroAtributo',
            fields=[
                ('patributo_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('patributo_nombre', models.CharField(max_length=200)),
                ('patributo_tabla', models.CharField(max_length=100)),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcalim.subcategoria')),
            ],
            options={
                'db_table': 'parametro_atributo',
            },
        ),
    ]
