# Generated by Django 5.1 on 2024-08-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcalim', '0012_parametroatributo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametroatributo',
            name='patributo_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
