# Generated by Django 5.1 on 2024-08-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcalim', '0013_alter_parametroatributo_patributo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametroatributo',
            name='patributo_label',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='parametroatributo',
            name='patributo_nivel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parametroatributo',
            name='patributo_orden',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
