# Generated by Django 5.1 on 2024-08-22 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcalim', '0016_inventario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='inv_cantidadactual',
            new_name='inv_cantidadActual',
        ),
    ]
