# Generated by Django 5.1 on 2024-08-22 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcalim', '0017_rename_inv_cantidadactual_inventario_inv_cantidadactual'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcalim.inventario')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcalim.venta')),
            ],
            options={
                'db_table': 'inventario_venta',
                'unique_together': {('venta', 'inv')},
            },
        ),
    ]
