# Generated by Django 5.1 on 2024-08-23 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcalim', '0019_categoria2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria2',
        ),
    ]
