# Generated by Django 5.1 on 2024-08-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcalim', '0021_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='venta_ticket',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
