# Generated by Django 5.1 on 2024-08-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcalim', '0022_venta_venta_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_fecha',
            new_name='ticket_fechaCreacion',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_fechaFinalizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_precioTotal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
