# Generated by Django 5.1 on 2024-08-26 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcalim', '0023_rename_ticket_fecha_ticket_ticket_fechacreacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appcalim.ticket'),
        ),
    ]
