# Generated by Django 5.1 on 2024-08-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcalim', '0024_venta_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='venta_fechaRegistro',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='venta_fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
