# Generated by Django 5.1 on 2024-09-01 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcalim', '0025_venta_venta_fecharegistro_alter_venta_venta_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='venta_precioTotal',
            new_name='venta_precioSubTotal',
        ),
    ]
