# Generated by Django 5.1 on 2024-09-02 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcalim', '0026_rename_venta_preciototal_venta_venta_preciosubtotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('ingreso_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ingreso_unidad', models.BigIntegerField(blank=True, null=True)),
                ('ingreso_costoUnitario', models.FloatField(blank=True, null=True)),
                ('ingreso_fecha', models.DateTimeField()),
                ('ingreso_fechaInventario', models.DateTimeField(blank=True, null=True)),
                ('ingreso_fechaEliminacion', models.DateTimeField(blank=True, null=True)),
                ('ingreso_estado', models.CharField(max_length=50)),
                ('ingreso_referencia', models.CharField(blank=True, max_length=200, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcalim.producto')),
            ],
            options={
                'db_table': 'ingreso',
            },
        ),
    ]
