# Generated by Django 5.1 on 2024-09-07 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcalim', '0027_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='ingreso_costoTotal',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
