# Generated by Django 5.1 on 2024-09-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcalim', '0028_ingreso_ingreso_costototal'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='ingreso_fechaCierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
