# Generated by Django 5.1 on 2024-09-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcalim', '0029_ingreso_ingreso_fechacierre'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='ingreso_porcentajeGanancia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='ingreso_precioUnitario',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
