# Generated by Django 5.1 on 2024-09-11 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcalim', '0030_ingreso_ingreso_porcentajeganancia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='ingreso_ganancia',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
