# Generated by Django 5.1 on 2024-09-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcalim', '0031_ingreso_ingreso_ganancia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='inv_fechaUltActualizacion',
        ),
        migrations.AddField(
            model_name='inventario',
            name='inv_estado',
            field=models.CharField(default='V', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario',
            name='inv_fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
