# Generated by Django 5.1 on 2024-09-15 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcalim', '0032_remove_inventario_inv_fechaultactualizacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcalim.ingreso')),
                ('inv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcalim.inventario')),
            ],
            options={
                'db_table': 'inventario_ingreso',
                'unique_together': {('inv', 'ingreso')},
            },
        ),
    ]
