# Generated by Django 5.1 on 2024-09-25 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcalim', '0033_inventarioingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='producto_fechaActualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
