# Generated by Django 5.1 on 2024-10-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcalim', '0034_producto_producto_fechaactualizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='producto_nombreDesc',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='producto_nombreMarca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='producto_nombreMedida',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='producto_nombreTipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
