# Generated by Django 5.1 on 2024-11-12 01:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcalim', '0037_alter_ingreso_ingreso_costototal'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='ingreso_comprador',
            field=models.CharField(default='comprador01', max_length=100),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='ingreso_fechaCompra',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
