# Generated by Django 5.1 on 2024-11-17 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcalim', '0039_producto_producto_sigla'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresoproducto',
            name='producto',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='appcalim.producto'),
        ),
    ]
