# Generated by Django 5.1 on 2024-11-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcalim', '0041_item_delete_ingresoproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_correlativo',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_fechaBaja',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_fechaRegistro',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
