# Generated by Django 5.1 on 2024-11-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcalim', '0042_item_item_correlativo_item_item_fechabaja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='ingreso_unidad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
