# Generated by Django 5.1 on 2024-11-26 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcalim', '0043_alter_ingreso_ingreso_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='ingreso_categoriaFechaVto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='ingreso_unidad',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
