# Generated by Django 5.1 on 2024-11-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcalim', '0044_ingreso_ingreso_categoriafechavto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='ingreso_categoriaFechaVto',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
