# Generated by Django 5.1 on 2024-12-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcalim', '0045_alter_ingreso_ingreso_categoriafechavto'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='subcategoria_descripcion',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='subcategoria_marca',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='subcategoria_medida',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
