# Generated by Django 5.1 on 2024-12-14 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcalim', '0046_subcategoria_subcategoria_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoria',
            name='subcategoria_descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
