# Generated by Django 5.1 on 2024-12-14 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcalim', '0047_alter_subcategoria_subcategoria_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategoria',
            old_name='subcategoria_descripcion',
            new_name='subcategoria_tipo',
        ),
    ]
